receivers:

  awsecscontainermetricsd:
    sidecar: true

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      scrape_configs:
      - job_name: otel-collector-metrics
        scrape_interval: 60s
        static_configs:
        - targets: ['localhost:8888']

  filelog:
    start_at: end
    include:
      - C:\hostfs\ProgramData\docker\containers\*\*-json.log
    include_file_path: true
    operators:
      - type: move
        from: attributes["log.file.name"]
        to: resource["log.file.name"]

processors:
  batch:

exporters:

  logging:
    verbosity: normal

  coralogix:
    domain: "$CORALOGIX_DOMAIN"
    private_key: "$PRIVATE_KEY"
    application_name: "$APP_NAME"
    subsystem_name: "$SUB_SYS"
    application_name_attributes:
    - "$APP_NAME"
    - "aws.ecs.cluster"
    - "aws.ecs.cluster.name"
    - "aws.ecs.task.definition.family"
    - "container.name"
    subsystem_name_attributes:
    - "$SUB_SYS"
    - "aws.ecs.task.family"
    - "aws.ecs.container.name"
    - "aws.ecs.docker.name"
    timeout: 30s

extensions:
  health_check:

service:

  extensions:
    - health_check

  pipelines:

    metrics:
      receivers:
        - otlp
        - awsecscontainermetricsd
      processors:
        - batch
      exporters:
        - coralogix
        - logging

    logs:
      receivers:
        - otlp
        - filelog
      processors:
        - batch
      exporters:
        - coralogix
        - logging

    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - coralogix
        - logging
