receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
  prometheus:
    config:
      scrape_configs:
      - job_name: otel-collector-metrics
        scrape_interval: 60s
        static_configs:
        - targets: ['localhost:8888']
  awsecscontainermetricsd:
  filelog:
    start_at: end
    include:
      - /hostfs/var/lib/docker/containers/*/*.log
    include_file_path: true
    # add log.file.path to resource attributes
    operators:
      - type: json_parser
        parse_from: body
        parse_to: body
        timestamp:
          parse_from: body.time
          layout: '%Y-%m-%dT%H:%M:%S.%fZ'

      - type: recombine
        id: recombine
        combine_field: body.log
        source_identifier: attributes["log.file.path"]
        is_last_entry: body.log endsWith "\n"
        force_flush_period: 10s
        on_error: drop
        combine_with: ""

      - type: move
        from: attributes["log.file.path"]
        to: resource["log.file.path"]

processors:
  resourcedetection:
    # ecs & docker detectors not required when using ecslogresourcedetection for logs
    detectors: [env, ec2, system]
    timeout: 2s
    override: false
  ecsattributes:
    container_id:
      sources:
        - "log.file.path"
  transform/logs:
    error_mode: ignore
    log_statements:
      - context: resource
        statements:
          - set(attributes["cx_container_id"], attributes["docker.id"])
          - set(attributes["aws_ecs_task_family"], attributes["aws.ecs.task.definition.family"])
          - set(attributes["image_id"], attributes["image.id"])
          - delete_key(attributes, "image.id")
  batch:
    send_batch_size: 1024
    send_batch_max_size: 2048
    timeout: "1s"
  # otel-collector resource detection for collector
  resourcedetection/otel-collector:
    detectors: [ecs, ec2]
    timeout: 2s
    override: false

exporters:
  logging:
  coralogix:
    domain: "$CORALOGIX_DOMAIN"
    private_key: "$PRIVATE_KEY"
    application_name: "$APP_NAME"
    subsystem_name: "$SUB_SYS"
    application_name_attributes:
    - "aws.ecs.cluster"
    - "aws.ecs.cluster.name"
    - "aws.ecs.task.definition.family"
    subsystem_name_attributes:
    - "aws.ecs.container.name"
    - "aws.ecs.docker.name"
    - "docker.name"
    timeout: 30s

extensions:
  health_check:

service:
  extensions:
    - health_check
  telemetry:
    logs:
      level: warn
    metrics:
      address: 0.0.0.0:8888
      level: detailed
  pipelines:
    logs:
      receivers:
        - filelog
      processors:
        # - resourcedetection # For logs relayed from other containers, don't use otel container's resource attributes.
        - ecsattributes
        - transform/logs
        - batch
      exporters:
        - coralogix
    metrics:
      receivers:
        - otlp
        - awsecscontainermetricsd
      processors:
        - batch
      exporters:
        - coralogix
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - coralogix
    metrics/otel-collector:
      receivers:
        - prometheus
      processors:
        - resourcedetection/otel-collector
        - batch
      exporters:
        - coralogix
