name: Changelog
on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches: [master]
    paths:
      - "modules/**"

permissions:
  contents: read
jobs:   
  check-changelog-updates:
    # if the PR has the 'skip changelog' label, skip the changelog check 
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip changelog') }}
    runs-on: ubuntu-latest
    name: Check Changelog Update
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47.0.0
        with:
          files: |
            **/CHANGELOG.md

      - name: Fail if no changelog update
        run: |
          if [[ "${{ steps.changed-files.outputs.all_changed_files }}" = "" ]]; then
            echo "Please add a changelog entry in CHANGELOG.md or add 'skip changelog' label to your PR if this change does not require an entry".
            exit 1
          fi
