name: PR Title Check

on:
  pull_request:
    branches: [master]
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write
jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title follows conventional commits
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
          validateSingleCommit: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
