name: emantic-pull-request

on:
  pull_request:
    branches: [master]
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  semantic-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title follows release format
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            fix
            feat
            major
            docs
            chore
            ci
            test
          requireScope: false
          validateSingleCommit: false
          subjectPattern: ^.{1,}$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            doesn't match the configured pattern. Please ensure that the subject
            describes what the PR does.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
