name: semantic-pull-request

on:
  pull_request:
    branches: [master]
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  semantic-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title follows release format
        uses: amannn/action-semantic-pull-request@04a8d177d951f6d3dff9f6fbfa336354c60a1112 # v6.0.0
        with:
          types: |
            fix
            feat
            major
            docs
            chore
            ci
            test
          requireScope: false
          validateSingleCommit: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
