name: semantic-pull-request

on:
  pull_request:
    branches: [master]
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  semantic-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title follows release format
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        with:
          types: |
            fix
            feat
            major
            docs
            chore
            ci
            test
          requireScope: false
          validateSingleCommit: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
